"""Keybinding loading.

A version-controlled ``default_keybindings.yaml`` ships with the repo. On
startup, if the user's ``keybindings.yaml`` (gitignored) is missing it is
generated by copying the defaults. The user file is what the app actually reads.
"""

from __future__ import annotations

import shutil
from pathlib import Path

import pygame
import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_PATH = ROOT / "default_keybindings.yaml"
USER_PATH = ROOT / "keybindings.yaml"

# Logical actions the app cares about.
ACTIONS = [
    "open_palette",
    "create",
    "delete",
    "move_left",
    "move_right",
    "move_up",
    "move_down",
    "point",
    "keybindings",
    "confirm",
    "cancel",
]


class Keybindings:
    def __init__(self, mapping: dict[str, str]):
        self.mapping = mapping

    @classmethod
    def load(cls) -> "Keybindings":
        if not USER_PATH.exists():
            if DEFAULT_PATH.exists():
                shutil.copyfile(DEFAULT_PATH, USER_PATH)
            else:
                USER_PATH.write_text("")
        with USER_PATH.open("r", encoding="utf-8") as fh:
            data = yaml.safe_load(fh) or {}
        # Backfill any missing actions from defaults so the app never crashes.
        defaults = {}
        if DEFAULT_PATH.exists():
            with DEFAULT_PATH.open("r", encoding="utf-8") as fh:
                defaults = yaml.safe_load(fh) or {}
        mapping = {a: str(data.get(a, defaults.get(a, ""))) for a in ACTIONS}
        return cls(mapping)

    def save(self) -> None:
        with USER_PATH.open("w", encoding="utf-8") as fh:
            yaml.safe_dump(self.mapping, fh, sort_keys=False)

    def keycode(self, action: str) -> int:
        """pygame key constant for an action, e.g. 'd' -> pygame.K_d."""
        name = self.mapping.get(action, "")
        return key_name_to_code(name)

    def label(self, action: str) -> str:
        return self.mapping.get(action, "").upper()

    def matches(self, action: str, key: int) -> bool:
        return key == self.keycode(action)


def key_name_to_code(name: str) -> int:
    name = (name or "").strip().lower()
    if not name:
        return -1
    # pygame.key.key_code understands names like "left", "return", "d".
    try:
        return pygame.key.key_code(name)
    except (ValueError, Exception):
        # Fall back to K_<name> lookup for things like "lctrl".
        const = getattr(pygame, f"K_{name.upper()}", None)
        return const if isinstance(const, int) else -1


def code_to_key_name(code: int) -> str:
    try:
        return pygame.key.name(code)
    except Exception:
        return ""
